### ISSUE TITLE
Compatible with HA Docker?

### ISSUE THREAD

**Issue by foocode** [albertogeniola/ha-meross-local-broker#43]
Hi,

I am trying to achieve cloudless Meross device control in my HA install. I run HA via the official docker image.
In the Local Broker .md it mentions; "This addon has been tested on Homeassistant Docker environment..."

Yet I understand installation is not possible via the provided link as HA docker environments do not support the store/addons. Clicking the following results in the message "This redirect is not supported by your Home Assistant installation. It needs either the Home Assistant Operating System or Home Assistant Supervised installation method. For more information, see the documentation.".

https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Falbertogeniola%2Fha-meross-local-broker

Is there another way to use or install with HA docker?

Thanks!

**Comment by albertogeniola** [comment]
Hi!
I've not tested it extensively, but you should be able to run the addon container as standalone on the same PC/server where you run your HA docker. You won't be able to access the UI via HomeAssistant, but you could always access it directly by exposing the management port. 

I might invest some time to document the entire process. For now, here's what you can try.

1. Build the container image.

```docker build --build-arg BUILD_ARCH="amd64" --build-arg BUILD_FROM="ghcr.io/home-assistant/amd64-base-debian:buster" -t local/meross_local_broker "meross_local_broker"
```

2. Run the image locally 
```
docker run --name meross_local_broker --rm  --privileged -p 2001:2001/tcp -p 2003:2003/tcp -p 10001:10001/tcp --env expose_admin_api=true --env advertise=false --env debug_mode=true --env debug_port=10001 --mount type=bind,source=$PWD/meross_local_broker/rootfs/opt/custom_broker,target=/opt/custom_broker -v $PWD/.local_debug/data:/data local/meross_local_broker
```

The mDNS advertisement might not work, so you will probably need to input the IP of container manually when you setup the HA integration. Apart from that, it should work. Let me know!

**Comment by foocode** [comment]
Thank you @albertogeniola, I will give that a go - though it may take some time to report back as building an image will be new learnings for me! Thanks for your response & thank you for your efforts in this space.

**Comment by didn0t** [comment]
How do you build it - your command above is missing.  Normal docker build fails.

**Comment by albertogeniola** [comment]
Hi!
I've update the message and now the build command is shown. Sorry about that.

**Comment by Gandulf78** [comment]
Hi. 
I am trying to build it but I receive the following error message:

unable to prepare context: path "meross_local_broker" not found

**Comment by nojszewski** [comment]
It's not working for me :(

I had to change the Dockerfile because it was throwing some errors, I turned it all into docker-compose, and once the container is built from the image and starts, it keeps restarting. I have something like this in the logs:

my docker-compose:

```
services:
  meross_local_broker:
    build:
      context: ./meross_local_broker
      dockerfile: Dockerfile
      args:
        BUILD_ARCH: amd64
        MOSQUITTO_GO_AUTH_VERSION: 1.5.0
        BUILD_FROM: ghcr.io/home-assistant/amd64-base-debian:buster
    container_name: meross_local_broker
    privileged: true
    ports:
      - "2001:2001"
      - "2003:2003"
      - "10001:10001"
    environment:
      - expose_admin_api=true
      - advertise=false
      - debug_mode=true
      - debug_port=10001
    volumes:
      - ./meross_local_broker/rootfs/opt/custom_broker:/opt/custom_broker
      - ./.local_debug/data:/data
    restart: unless-stopped
```

```

meross_local_broker  | cont-init: info: running /etc/cont-init.d/60-nginx.sh
meross_local_broker  | [14:25:36] INFO: Substituting ingress_entry with /
meross_local_broker  | [14:25:36] INFO: Substituting interface with 0.0.0.0
meross_local_broker  | [14:25:36] INFO: Substituting port with 2003
meross_local_broker  | [14:25:36] WARNING: Exposing nginx publicly due to expose_admin_api env variable.
meross_local_broker  | cont-init: info: /etc/cont-init.d/60-nginx.sh exited 0
meross_local_broker  | cont-init: warning: some scripts exited nonzero
meross_local_broker  | s6-rc: warning: unable to start service legacy-cont-init: command exited 1
meross_local_broker  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
meross_local_broker  | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
meross_local_broker  | s6-rc: info: service fix-attrs: stopping
meross_local_broker  | s6-rc: info: service fix-attrs successfully stopped
meross_local_broker  | s6-rc: info: service s6rc-oneshot-runner: stopping
meross_local_broker  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
